package com.mycompany.cop4331.project_final;

import javax.swing.*;
import java.awt.event.*;

public class AdminPanelUI extends JFrame {

    /**
     * Creates new form AdminPanelUI
     */
    public AdminPanelUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        contentPane = new javax.swing.JPanel();
        logoPane = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        head_Administrator = new javax.swing.JLabel();
        head_Dashboard = new javax.swing.JLabel();
        menuPane = new javax.swing.JPanel();
        create_new_user = new javax.swing.JButton();
        pending_Sellers = new javax.swing.JButton();
        active_sellers = new javax.swing.JButton();
        orders = new javax.swing.JButton();
        displayPane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contentPane.setBackground(new java.awt.Color(255, 255, 255));

        logoPane.setBackground(new java.awt.Color(255, 255, 255));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/cop4331/project_final/logo1.png"))); // NOI18N

        head_Administrator.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        head_Administrator.setForeground(new java.awt.Color(204, 0, 51));
        head_Administrator.setText("Administrator");

        head_Dashboard.setBackground(new java.awt.Color(255, 255, 255));
        head_Dashboard.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        head_Dashboard.setText("Dashboard");

        javax.swing.GroupLayout logoPaneLayout = new javax.swing.GroupLayout(logoPane);
        logoPane.setLayout(logoPaneLayout);
        logoPaneLayout.setHorizontalGroup(
            logoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo)
                .addGroup(logoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logoPaneLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(head_Administrator, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(logoPaneLayout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(head_Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logoPaneLayout.setVerticalGroup(
            logoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPaneLayout.createSequentialGroup()
                .addGroup(logoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo)
                    .addGroup(logoPaneLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(head_Administrator, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(head_Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuPane.setBackground(new java.awt.Color(255, 255, 255));

        create_new_user.setBackground(new java.awt.Color(102, 102, 102));
        create_new_user.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        create_new_user.setText("Create New User");
        create_new_user.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        create_new_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_new_userActionPerformed(evt);
            }
        });

        pending_Sellers.setBackground(new java.awt.Color(102, 102, 102));
        pending_Sellers.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        pending_Sellers.setText("Pending Sellers");
        pending_Sellers.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pending_Sellers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pending_SellersActionPerformed(evt);
            }
        });

        active_sellers.setBackground(new java.awt.Color(102, 102, 102));
        active_sellers.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        active_sellers.setText("Active Sellers");
        active_sellers.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        active_sellers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                active_sellersActionPerformed(evt);
            }
        });

        orders.setBackground(new java.awt.Color(102, 102, 102));
        orders.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        orders.setText("Orders");
        orders.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        orders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPaneLayout = new javax.swing.GroupLayout(menuPane);
        menuPane.setLayout(menuPaneLayout);
        menuPaneLayout.setHorizontalGroup(
            menuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(create_new_user, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(pending_Sellers, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(active_sellers, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(orders, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        menuPaneLayout.setVerticalGroup(
            menuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pending_Sellers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(create_new_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orders, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(active_sellers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
/* 
        displayPane.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                displayPaneAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
*/
        javax.swing.GroupLayout displayPaneLayout = new javax.swing.GroupLayout(displayPane);
        displayPane.setLayout(displayPaneLayout);
        displayPaneLayout.setHorizontalGroup(
            displayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        displayPaneLayout.setVerticalGroup(
            displayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout contentPaneLayout = new javax.swing.GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentPaneLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(menuPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(displayPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menuPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(displayPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contentPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contentPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/* 
    private void displayPaneAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_displayPaneAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_displayPaneAncestorAdded
*/
    private void ordersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersActionPerformed
        OrdersUI obj = new OrdersUI();
        obj.setVisible(true);
    }//GEN-LAST:event_ordersActionPerformed

    private void active_sellersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_active_sellersActionPerformed
        ActiveSellersUI obj = new ActiveSellersUI();
        obj.setVisible(true);
    }//GEN-LAST:event_active_sellersActionPerformed

    private void pending_SellersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pending_SellersActionPerformed
        PendingSellersUI obj = new PendingSellersUI();
        obj.setVisible(true);
    }//GEN-LAST:event_pending_SellersActionPerformed

    private void create_new_userActionPerformed(ActionEvent evt) {//GEN-FIRST:event_create_new_userActionPerformed
        CreateNewUserUI obj = new CreateNewUserUI();
        obj.setVisible(true);
    }//GEN-LAST:event_create_new_userActionPerformed
/* 
    private void displayPaneAncestorAdded(javax.swing.event.AncestorEvent evt) {                                          
        PendingSellersUI obj = new PendingSellersUI();
        obj.setVisible(true);
    }
*/
  

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanelUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanelUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanelUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanelUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanelUI().setVisible(true);   
            }
        });
        
        //AdminPanelUI obj = new AdminPanelUI();
        //JFrame frame = new AdminPanelUI();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton active_sellers;
    private javax.swing.JPanel contentPane;
    private javax.swing.JButton create_new_user;
    private javax.swing.JPanel displayPane;
    private javax.swing.JLabel head_Administrator;
    private javax.swing.JLabel head_Dashboard;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel logoPane;
    private javax.swing.JPanel menuPane;
    private javax.swing.JButton orders;
    private javax.swing.JButton pending_Sellers;
    // End of variables declaration//GEN-END:variables
}
