/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pages_Jeff_Seller;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import datebase_jon.Product;
import datebase_jon.Review;
import datebase_jon.ShopletSystemManager;
import net.miginfocom.swing.MigLayout;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

import javax.swing.GroupLayout.Alignment;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.border.Border;

/**
 *
 * @author jeffplatel
 */
public class ProductUI extends javax.swing.JFrame {

    Product product;

    /**
     * Creates new form ProductUI
     */
    public ProductUI(Product product) {
    	setTitle("Seller Product - " + product.name);
    	this.product = product;
        initComponents();
    }
    
    public void refreshUI(String newName, String newPrice, String newDescription)
    {
    	setTitle("Seller Product - " + newName);
        product_name.setText(newName);
        price.setText("Price: " + newPrice);
        description.setText(newDescription);
        System.out.println("UI Elements updated");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPane = new javax.swing.JPanel();
        product_name = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        edit_details = new javax.swing.JButton();
        edit_details.setForeground(new Color(255, 255, 255));
        delete = new javax.swing.JButton();
        delete.setForeground(new Color(255, 255, 255));
        discount_code = new javax.swing.JButton();
        discount_code.setForeground(new Color(255, 255, 255));
        reviews = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        back_button = new javax.swing.JButton();
        back_button.setForeground(new Color(255, 255, 255));

        contentPane.setBackground(new Color(240, 240, 240));

        product_name.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        product_name.setText(product.name);

        price.setText("Price: " + product.price);

        edit_details.setBackground(new java.awt.Color(102, 102, 102));
        edit_details.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        edit_details.setText("Edit Details");
        edit_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_detailsActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(102, 102, 102));
        delete.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        discount_code.setBackground(new java.awt.Color(102, 102, 102));
        discount_code.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        discount_code.setText("Discount  Code");
        discount_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discount_codeActionPerformed(evt);
            }
        });

        reviews.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        reviews.setText("Reviews");

        description.setColumns(20);
        description.setRows(5);
        description.setText(product.description);
        jScrollPane1.setViewportView(description);

        back_button.setBackground(new java.awt.Color(102, 102, 102));
        back_button.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        back_button.setText("Back");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });
        
        JPanel reviewPanel = new JPanel();

        javax.swing.GroupLayout contentPaneLayout = new javax.swing.GroupLayout(contentPane);
        contentPaneLayout.setHorizontalGroup(
        	contentPaneLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(contentPaneLayout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(reviewPanel, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
        				.addGroup(contentPaneLayout.createSequentialGroup()
        					.addGroup(contentPaneLayout.createParallelGroup(Alignment.LEADING)
        						.addGroup(contentPaneLayout.createParallelGroup(Alignment.LEADING, false)
        							.addComponent(price, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(product_name, GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
        						.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 564, GroupLayout.PREFERRED_SIZE)
        						.addComponent(reviews, GroupLayout.PREFERRED_SIZE, 135, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
        					.addGroup(contentPaneLayout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(delete, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(edit_details, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(discount_code, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(back_button, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        			.addGap(16))
        );
        contentPaneLayout.setVerticalGroup(
        	contentPaneLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(contentPaneLayout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(contentPaneLayout.createParallelGroup(Alignment.TRAILING, false)
        				.addGroup(contentPaneLayout.createSequentialGroup()
        					.addComponent(product_name, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(price, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 207, GroupLayout.PREFERRED_SIZE)
        					.addGap(37)
        					.addComponent(reviews, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED))
        				.addGroup(contentPaneLayout.createSequentialGroup()
        					.addComponent(back_button, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addGap(18)
        					.addComponent(edit_details, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(delete, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(discount_code, GroupLayout.PREFERRED_SIZE, 84, GroupLayout.PREFERRED_SIZE)
        					.addGap(35)))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(reviewPanel, GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
        			.addContainerGap())
        );
        contentPane.setLayout(contentPaneLayout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        
        //Reviews
        List<Review> productReviews = ShopletSystemManager.getInstance().grab_reviews(product.product_id);
                
        for (int i = 0; i < productReviews.size(); i++)
        {
        	reviewPanel.add(addReviewItem(productReviews.get(i).review_id, productReviews.get(i).user_id
            		,productReviews.get(i).product_id, productReviews.get(i).reviewer_name, productReviews.get(i).review_rating
            		, productReviews.get(i).review_content), "span, growx");
        }
        
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void discount_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discount_codeActionPerformed
        DiscountCodeUI obj = new DiscountCodeUI();
        obj.setVisible(true);
    }//GEN-LAST:event_discount_codeActionPerformed
    private void edit_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_detailsActionPerformed
        EditDetailsUI obj = new EditDetailsUI(product, this);
        obj.setVisible(true);
    }//GEN-LAST:event_edit_detailsActionPerformed
    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        if(delete.getMouseListeners() != null){
        	ShopletSystemManager.getInstance().delete_product(product.product_id);
            contentPane.setVisible(false);
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame, "Product successefully deleted.");
            dispose();
        }
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * The JPanel object that represents a product item entry in the product catalog.
     * @param productName The name of the product to show
     * @param productPrice The price of the product to show
     * @return
     */
    public JPanel addReviewItem(Integer review_id, Integer user_id, Integer product_id, String review_name, String review_rating, String review_content)
    {
    	Review review = new Review(review_id, user_id, product_id, review_name, review_rating, review_content);
    	
        // Convert price to 2 decimal places
        Border border = BorderFactory.createLineBorder(Color.black);

        // Build product entry
        JPanel reviewPanel = new JPanel(new MigLayout("", "[][]push[][]15", "[]"));
        reviewPanel.setPreferredSize(new Dimension(1000, 60));
        reviewPanel.setMaximumSize(new Dimension(1000, 60));
        reviewPanel.setBackground(Color.white);
        
        JLabel reviewerLabel = new JLabel(review.reviewer_name);
        reviewerLabel.setFont(new Font("Arial", Font.PLAIN, 28));
        reviewerLabel.setMaximumSize(new Dimension(200, 100));
        reviewPanel.add(reviewerLabel);
        
        reviewPanel.add(new JLabel(" Rating: " + review_rating)).setFont(new Font("Arial", Font.PLAIN, 16));
        reviewPanel.add(new JLabel(review_content)).setFont(new Font("Arial", Font.PLAIN, 16));
        

        reviewPanel.setBorder(border);

        // Return the product panel
        return reviewPanel;
    }
    
    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_back_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductUI(new Product()).setVisible(true);
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_button;
    private javax.swing.JPanel contentPane;
    private javax.swing.JButton delete;
    private javax.swing.JTextArea description;
    private javax.swing.JButton discount_code;
    private javax.swing.JButton edit_details;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel price;
    private javax.swing.JLabel product_name;
    private javax.swing.JLabel reviews;
}
