/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pages_Jeff_Seller;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import datebase_jon.ShopletSystemManager;
import datebase_jon.Order;
import datebase_jon.Product;
import javax.swing.JLabel;
import java.awt.Font;

/**
 *
 * @author jeffplatel
 */
public class ProfitReportUI extends javax.swing.JFrame {

    /**
     * Creates new form ProfitReportUI
     */
    public ProfitReportUI() {
    	setTitle("Seller Revenue Report");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPane = new javax.swing.JPanel();
        total_profit = new javax.swing.JLabel();
        profit = new javax.swing.JLabel();
        close_button = new javax.swing.JButton();
        close_button.setForeground(new Color(255, 255, 255));

        contentPane.setBackground(new Color(240, 240, 240));

        total_profit.setText("Gross Profit:");

        close_button.setBackground(new java.awt.Color(102, 102, 102));
        close_button.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        close_button.setText("Close");
        close_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        close_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_buttonActionPerformed(evt);
            }
        });
        
        JLabel lblProfitHeader = new JLabel("Profit Report");
        lblProfitHeader.setFont(new Font("Tahoma", Font.PLAIN, 25));
        
        

        javax.swing.GroupLayout contentPaneLayout = new javax.swing.GroupLayout(contentPane);
        contentPaneLayout.setHorizontalGroup(
        	contentPaneLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(contentPaneLayout.createSequentialGroup()
        			.addGroup(contentPaneLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(contentPaneLayout.createSequentialGroup()
        					.addGap(78)
        					.addComponent(lblProfitHeader))
        				.addGroup(contentPaneLayout.createSequentialGroup()
        					.addGap(102)
        					.addComponent(total_profit)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(profit)))
        			.addContainerGap(71, Short.MAX_VALUE))
        		.addGroup(contentPaneLayout.createSequentialGroup()
        			.addContainerGap(91, Short.MAX_VALUE)
        			.addComponent(close_button, GroupLayout.PREFERRED_SIZE, 114, GroupLayout.PREFERRED_SIZE)
        			.addGap(85))
        );
        contentPaneLayout.setVerticalGroup(
        	contentPaneLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, contentPaneLayout.createSequentialGroup()
        			.addGap(26)
        			.addComponent(lblProfitHeader)
        			.addGap(39)
        			.addGroup(contentPaneLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(total_profit, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        				.addComponent(profit))
        			.addPreferredGap(ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
        			.addComponent(close_button, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
        			.addGap(54))
        );
        contentPane.setLayout(contentPaneLayout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        
        //Get the total profit.
        
    	List<Order> orders = ShopletSystemManager.getInstance().get_all_orders();
    	List<Product> sellerProductIds = ShopletSystemManager.getInstance().get_list_of_own_products();
    	
    	Integer totalProfit = 0;
    	List<String> orderProductIds = new ArrayList<String>();
    	
    	for (int i = 0; i < orders.size(); i++)
    	{
    		orderProductIds.addAll(Arrays.asList(orders.get(i).product_ids.replaceAll("[^0-9,]","").split(",")));
    	}
    	
    	System.out.println("Product IDS that were bought:");
		System.out.println(orderProductIds.toString());
		
		System.out.println("First Product Id that was found for this seller: " + sellerProductIds.get(0).product_id);
		
		for (int i = 0; i < orderProductIds.size(); i++)
		{
			for (int j = 0; j < sellerProductIds.size(); j++)
			{
				if (Integer.parseInt(orderProductIds.get(i)) == sellerProductIds.get(j).product_id)
					totalProfit += sellerProductIds.get(j).getProductPrice();
			}
		}
			
    	profit.setText("$" + totalProfit.toString());
    	

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_buttonActionPerformed
    	this.setVisible(false);
    }//GEN-LAST:event_close_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfitReportUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfitReportUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfitReportUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfitReportUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfitReportUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close_button;
    private javax.swing.JPanel contentPane;
    private javax.swing.JLabel profit;
    private javax.swing.JLabel total_profit;
}
