/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pages_Jeff_Seller;

/**
 *
 * @author jeffplatel
 */

import java.awt.event.*;
import java.util.List;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout.ParallelGroup;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.border.Border;

import datebase_jon.Product;
import datebase_jon.ShopletSystemManager;
import datebase_jon.User;
import net.miginfocom.swing.MigLayout;
import pages_jarold.Login;
import pages_kelvin.Cart;

import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.BoxLayout;

public class SellersPanelUI extends javax.swing.JFrame {

    /**
     * Creates new form ProductCatalog
     */
    public SellersPanelUI() {
    	setTitle("Sellers Portal");
    	addWindowListener(new WindowAdapter() {
        	@Override
        	public void windowActivated(WindowEvent e) {
        		// Update cart text button when user focuses on window.
        		System.out.println("Product list refreshed");
        		refreshProductList();
        	}
        });
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPane = new javax.swing.JPanel();
        headerPane = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        seller_header = new javax.swing.JLabel();
        logout_button = new javax.swing.JButton();
        logout_button.setForeground(new Color(255, 255, 255));
        displayPane = new javax.swing.JPanel();
        menuPane = new javax.swing.JPanel();
        profile_button = new javax.swing.JButton();
        profile_button.setForeground(new Color(255, 255, 255));
        add_product_button = new javax.swing.JButton();
        add_product_button.setForeground(new Color(255, 255, 255));
        profit_report_button = new javax.swing.JButton();
        profit_report_button.setForeground(new Color(255, 255, 255));
        product1 = new javax.swing.JPanel();
        product_name1 = new javax.swing.JLabel();
        cost1 = new javax.swing.JLabel();
        view_button1 = new javax.swing.JButton();
        view_button1.setForeground(new Color(255, 255, 255));
        product2 = new javax.swing.JPanel();
        product_name2 = new javax.swing.JLabel();
        cost2 = new javax.swing.JLabel();
        view_button2 = new javax.swing.JButton();
        view_button2.setForeground(new Color(255, 255, 255));

        contentPane.setBackground(new Color(240, 240, 240));

        headerPane.setBackground(new Color(240, 240, 240));

        icon.setIcon(new ImageIcon(SellersPanelUI.class.getResource("/pages_Jeff_Seller/icon/logo1.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        seller_header.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        seller_header.setForeground(new java.awt.Color(204, 0, 51));
        seller_header.setText("Seller");

        logout_button.setBackground(new java.awt.Color(102, 102, 102));
        logout_button.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        logout_button.setText("Logout");
        logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerPaneLayout = new javax.swing.GroupLayout(headerPane);
        headerPaneLayout.setHorizontalGroup(
        	headerPaneLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(headerPaneLayout.createSequentialGroup()
        			.addComponent(icon)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(seller_header)
        			.addPreferredGap(ComponentPlacement.RELATED, 719, Short.MAX_VALUE)
        			.addComponent(logout_button, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        headerPaneLayout.setVerticalGroup(
        	headerPaneLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(headerPaneLayout.createSequentialGroup()
        			.addGroup(headerPaneLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(icon)
        				.addGroup(headerPaneLayout.createSequentialGroup()
        					.addGap(23)
        					.addComponent(seller_header, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
        				.addGroup(headerPaneLayout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(logout_button, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPane.setLayout(headerPaneLayout);

        displayPane.setBackground(new Color(240, 240, 240));

        menuPane.setBackground(new Color(240, 240, 240));

        profile_button.setBackground(new java.awt.Color(102, 102, 102));
        profile_button.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        profile_button.setText("Profile");
        profile_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profile_buttonActionPerformed(evt);
            }
        });

        add_product_button.setBackground(new java.awt.Color(102, 102, 102));
        add_product_button.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        add_product_button.setText("Add Product");
        add_product_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_product_buttonActionPerformed(evt);
            }
        });

        profit_report_button.setBackground(new java.awt.Color(102, 102, 102));
        profit_report_button.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        profit_report_button.setText("Profit Report");
        profit_report_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profit_report_buttonActionPerformed(evt);
            }
        });
        
        productList = new JPanel();
        productList.setBackground(new Color(240, 240, 240));

        javax.swing.GroupLayout menuPaneLayout = new javax.swing.GroupLayout(menuPane);
        menuPaneLayout.setHorizontalGroup(
        	menuPaneLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(menuPaneLayout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(menuPaneLayout.createParallelGroup(Alignment.TRAILING, false)
        				.addComponent(productList, GroupLayout.PREFERRED_SIZE, 960, GroupLayout.PREFERRED_SIZE)
        				.addGroup(menuPaneLayout.createSequentialGroup()
        					.addComponent(profile_button, GroupLayout.PREFERRED_SIZE, 172, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(add_product_button, GroupLayout.PREFERRED_SIZE, 171, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(profit_report_button, GroupLayout.PREFERRED_SIZE, 173, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap())
        );
        menuPaneLayout.setVerticalGroup(
        	menuPaneLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(menuPaneLayout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(menuPaneLayout.createParallelGroup(Alignment.LEADING, false)
        				.addGroup(menuPaneLayout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(profile_button, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE)
        					.addComponent(add_product_button, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE))
        				.addComponent(profit_report_button, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(productList, GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        			.addContainerGap())
        );
        productList.setLayout(new BoxLayout(productList, BoxLayout.Y_AXIS));
        menuPane.setLayout(menuPaneLayout);
        
      
        javax.swing.GroupLayout displayPaneLayout = new javax.swing.GroupLayout(displayPane);        
                        
        displayPaneLayout.setHorizontalGroup(
        	displayPaneLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(displayPaneLayout.createSequentialGroup()
        			.addGap(0)
        			.addGroup(displayPaneLayout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(menuPane, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addGap(15, 15, Short.MAX_VALUE)))
        );
        displayPaneLayout.setVerticalGroup(
        	displayPaneLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(displayPaneLayout.createSequentialGroup()
        			.addComponent(menuPane, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addPreferredGap(ComponentPlacement.RELATED))
        );

        
        displayPane.setLayout(displayPaneLayout);
        
        javax.swing.GroupLayout contentPaneLayout = new javax.swing.GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(displayPane, javax.swing.GroupLayout.PREFERRED_SIZE, 972, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        
       
        //Products
        List<Product> products = ShopletSystemManager.getInstance().get_list_of_own_products(ShopletSystemManager.getInstance().current_user_id);
        
        for (int i = 0; i < products.size(); i++)
        {
        	productList.add(ProductItem(products.get(i).product_id ,products.get(i).name, products.get(i).price, products.get(i).description), "span, growx");
        }

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_product_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_product_buttonActionPerformed
        AddProductUI obj = new AddProductUI(this);
        obj.setVisible(true);
    }//GEN-LAST:event_add_product_buttonActionPerformed
    private void profit_report_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profit_report_buttonActionPerformed
        ProfitReportUI obj = new ProfitReportUI();
        obj.setVisible(true);
    }//GEN-LAST:event_profit_report_buttonActionPerformed
    private void logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_buttonActionPerformed
        Logout obj = new Logout();
        if(logout_button.getMouseListeners() != null){
            this.setVisible(false);
            Login login = new Login();
            login.setVisible(true);
            obj.getClass();
        }
        
    }//GEN-LAST:event_logout_buttonActionPerformed
    private void view_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_button2ActionPerformed
        ProductUI obj = new ProductUI(new Product());
        obj.setVisible(true);
    }//GEN-LAST:event_view_button2ActionPerformed
    private void profile_buttonActionPerformed(ActionEvent evt){
        ProfileUI obj = new ProfileUI();
        obj.setVisible(true);
    }
    
  
    /**
     * The JPanel object that represents a product item entry in the product catalog.
     * @param productName The name of the product to show
     * @param productPrice The price of the product to show
     * @return
     */
    public JPanel ProductItem(Integer productId,String productName, Integer productPrice, String productDescription)
    {
    	Product product = new Product(productId, productName, productPrice, productDescription, true, 1, false);
    	
        // Convert price to 2 decimal places
        Border border = BorderFactory.createLineBorder(Color.black);

        // Build product entry
        JPanel newProductPanel = new JPanel(new MigLayout("", "[][]push[][]15", "[]"));
        newProductPanel.setPreferredSize(new Dimension(1000, 60));
        newProductPanel.setMaximumSize(new Dimension(1000, 60));
        newProductPanel.setBackground(Color.white);
        
        JLabel productLabel = new JLabel(productName);
        productLabel.setFont(new Font("Arial", Font.PLAIN, 28));
        productLabel.setMaximumSize(new Dimension(200, 100));
        
        newProductPanel.add(productLabel);
        newProductPanel.add(new JLabel("Cost: $" + productPrice)).setFont(new Font("Arial", Font.PLAIN, 16));
        
        JButton viewProduct = new JButton("View Product");
        viewProduct.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		ProductUI obj = new ProductUI(product);
            	obj.setVisible(true);
        	}
        });
        
        newProductPanel.add(viewProduct);
        newProductPanel.setBorder(border);

        // Return the product panel
        return newProductPanel;
    }
    
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellersPanelUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellersPanelUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellersPanelUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellersPanelUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellersPanelUI().setVisible(true);
            }
        });
    }
    
    /**
     * Refresh the product list if needed.
     */
    public void refreshProductList()
    {
    	productList.removeAll();
    	productList.revalidate();
    	productList.repaint();
    	
    	 //Products
        List<Product> products = ShopletSystemManager.getInstance().get_list_of_own_products(ShopletSystemManager.getInstance().current_user_id);
        
        for (int i = 0; i < products.size(); i++)
        {
        	productList.add(ProductItem(products.get(i).product_id ,products.get(i).name, products.get(i).price, products.get(i).description), "span, growx");
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_product_button;
    private javax.swing.JPanel contentPane;
    private javax.swing.JLabel cost1;
    private javax.swing.JLabel cost2;
    private javax.swing.JPanel displayPane;
    private javax.swing.JPanel headerPane;
    private javax.swing.JLabel icon;
    private javax.swing.JButton logout_button;
    private javax.swing.JPanel menuPane;
    private javax.swing.JPanel product1;
    private javax.swing.JPanel product2;
    private javax.swing.JLabel product_name1;
    private javax.swing.JLabel product_name2;
    private javax.swing.JButton profile_button;
    private javax.swing.JButton profit_report_button;
    private javax.swing.JLabel seller_header;
    private javax.swing.JButton view_button1;
    private javax.swing.JButton view_button2;
    private JPanel productList;
}
