/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pages_Jeff_Seller;

/**
 *
 * @author jeffplatel
 */

import java.awt.event.*;

public class SellersPanelUI extends javax.swing.JFrame {

    /**
     * Creates new form ProductCatalog
     */
    public SellersPanelUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPane = new javax.swing.JPanel();
        headerPane = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        seller_header = new javax.swing.JLabel();
        logout_button = new javax.swing.JButton();
        displayPane = new javax.swing.JPanel();
        menuPane = new javax.swing.JPanel();
        catalog_button = new javax.swing.JButton();
        profile_button = new javax.swing.JButton();
        add_product_button = new javax.swing.JButton();
        profit_report_button = new javax.swing.JButton();
        product1 = new javax.swing.JPanel();
        product_name1 = new javax.swing.JLabel();
        cost1 = new javax.swing.JLabel();
        view_button1 = new javax.swing.JButton();
        product2 = new javax.swing.JPanel();
        product_name2 = new javax.swing.JLabel();
        cost2 = new javax.swing.JLabel();
        view_button2 = new javax.swing.JButton();
        product3 = new javax.swing.JPanel();
        product_name3 = new javax.swing.JLabel();
        cost3 = new javax.swing.JLabel();
        view_button3 = new javax.swing.JButton();
        product4 = new javax.swing.JPanel();
        product_name4 = new javax.swing.JLabel();
        cost4 = new javax.swing.JLabel();
        view_button4 = new javax.swing.JButton();
        product5 = new javax.swing.JPanel();
        product_name5 = new javax.swing.JLabel();
        cost5 = new javax.swing.JLabel();
        view_button5 = new javax.swing.JButton();
        product6 = new javax.swing.JPanel();
        product_name6 = new javax.swing.JLabel();
        cost6 = new javax.swing.JLabel();
        view_button6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contentPane.setBackground(new java.awt.Color(255, 255, 255));

        headerPane.setBackground(new java.awt.Color(255, 255, 255));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/cop4331/poject/seller/icon/logo1.png"))); // NOI18N

        seller_header.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        seller_header.setForeground(new java.awt.Color(204, 0, 51));
        seller_header.setText("Seller");

        logout_button.setBackground(new java.awt.Color(102, 102, 102));
        logout_button.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        logout_button.setText("Logout");
        logout_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerPaneLayout = new javax.swing.GroupLayout(headerPane);
        headerPane.setLayout(headerPaneLayout);
        headerPaneLayout.setHorizontalGroup(
            headerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPaneLayout.createSequentialGroup()
                .addComponent(icon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seller_header)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 748, Short.MAX_VALUE)
                .addComponent(logout_button, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headerPaneLayout.setVerticalGroup(
            headerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPaneLayout.createSequentialGroup()
                .addComponent(icon)
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(headerPaneLayout.createSequentialGroup()
                .addGroup(headerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPaneLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(seller_header, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(headerPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logout_button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        displayPane.setBackground(new java.awt.Color(255, 255, 255));

        menuPane.setBackground(new java.awt.Color(255, 255, 255));

        catalog_button.setBackground(new java.awt.Color(102, 102, 102));
        catalog_button.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        catalog_button.setText("Catalog");
        catalog_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        catalog_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catalog_buttonActionPerformed(evt);
            }
        });

        profile_button.setBackground(new java.awt.Color(102, 102, 102));
        profile_button.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        profile_button.setText("Profile");
        profile_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        profile_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profile_buttonActionPerformed(evt);
            }
        });

        add_product_button.setBackground(new java.awt.Color(102, 102, 102));
        add_product_button.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        add_product_button.setText("Add Product");
        add_product_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add_product_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_product_buttonActionPerformed(evt);
            }
        });

        profit_report_button.setBackground(new java.awt.Color(102, 102, 102));
        profit_report_button.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        profit_report_button.setText("Profit Report");
        profit_report_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        profit_report_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profit_report_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPaneLayout = new javax.swing.GroupLayout(menuPane);
        menuPane.setLayout(menuPaneLayout);
        menuPaneLayout.setHorizontalGroup(
            menuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(catalog_button, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(profile_button, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(add_product_button, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                .addComponent(profit_report_button, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        menuPaneLayout.setVerticalGroup(
            menuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(catalog_button, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(profile_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(add_product_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profit_report_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        product1.setBackground(new java.awt.Color(255, 255, 255));
        product1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        product_name1.setText("Product Name");

        cost1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        cost1.setText("Cost: XXX.XX");

        view_button1.setBackground(new java.awt.Color(102, 102, 102));
        view_button1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        view_button1.setText("View");
        view_button1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        view_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout product1Layout = new javax.swing.GroupLayout(product1);
        product1.setLayout(product1Layout);
        product1Layout.setHorizontalGroup(
            product1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(product_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cost1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 558, Short.MAX_VALUE)
                .addComponent(view_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        product1Layout.setVerticalGroup(
            product1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product1Layout.createSequentialGroup()
                .addGroup(product1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(product1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(view_button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(product1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(product1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cost1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(product_name1))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );

        product2.setBackground(new java.awt.Color(255, 255, 255));
        product2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        product_name2.setText("Product Name");

        cost2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        cost2.setText("Cost: XXX.XX");

        view_button2.setBackground(new java.awt.Color(102, 102, 102));
        view_button2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        view_button2.setText("View");
        view_button2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        view_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout product2Layout = new javax.swing.GroupLayout(product2);
        product2.setLayout(product2Layout);
        product2Layout.setHorizontalGroup(
            product2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(product_name2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cost2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(view_button2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        product2Layout.setVerticalGroup(
            product2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(product2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(product_name2)
                    .addComponent(cost2))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(product2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(view_button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        product3.setBackground(new java.awt.Color(255, 255, 255));
        product3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        product_name3.setText("Product Name");

        cost3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        cost3.setText("Cost: XXX.XX");

        view_button3.setBackground(new java.awt.Color(102, 102, 102));
        view_button3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        view_button3.setText("View");
        view_button3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        view_button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_button3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout product3Layout = new javax.swing.GroupLayout(product3);
        product3.setLayout(product3Layout);
        product3Layout.setHorizontalGroup(
            product3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(product_name3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cost3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(view_button3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        product3Layout.setVerticalGroup(
            product3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(product3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(product_name3)
                    .addComponent(cost3))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(product3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(view_button3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        product4.setBackground(new java.awt.Color(255, 255, 255));
        product4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        product_name4.setText("Product Name");

        cost4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        cost4.setText("Cost: XXX.XX");

        view_button4.setBackground(new java.awt.Color(102, 102, 102));
        view_button4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        view_button4.setText("View");
        view_button4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        view_button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_button4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout product4Layout = new javax.swing.GroupLayout(product4);
        product4.setLayout(product4Layout);
        product4Layout.setHorizontalGroup(
            product4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(product_name4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cost4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(view_button4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        product4Layout.setVerticalGroup(
            product4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(product4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(product_name4)
                    .addComponent(cost4))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(product4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(view_button4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        product5.setBackground(new java.awt.Color(255, 255, 255));
        product5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        product_name5.setText("Product Name");

        cost5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        cost5.setText("Cost: XXX.XX");

        view_button5.setBackground(new java.awt.Color(102, 102, 102));
        view_button5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        view_button5.setText("View");
        view_button5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        view_button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_button5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout product5Layout = new javax.swing.GroupLayout(product5);
        product5.setLayout(product5Layout);
        product5Layout.setHorizontalGroup(
            product5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(product_name5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cost5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 559, Short.MAX_VALUE)
                .addComponent(view_button5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        product5Layout.setVerticalGroup(
            product5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(product5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(product_name5)
                    .addComponent(cost5))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(product5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(view_button5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        product6.setBackground(new java.awt.Color(255, 255, 255));
        product6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        product_name6.setText("Product Name");

        cost6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        cost6.setText("Cost: XXX.XX");

        view_button6.setBackground(new java.awt.Color(102, 102, 102));
        view_button6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        view_button6.setText("View");
        view_button6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        view_button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_button6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout product6Layout = new javax.swing.GroupLayout(product6);
        product6.setLayout(product6Layout);
        product6Layout.setHorizontalGroup(
            product6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(product_name6, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cost6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 558, Short.MAX_VALUE)
                .addComponent(view_button6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        product6Layout.setVerticalGroup(
            product6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(product6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(product_name6)
                    .addComponent(cost6))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(product6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(view_button6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout displayPaneLayout = new javax.swing.GroupLayout(displayPane);
        displayPane.setLayout(displayPaneLayout);
        displayPaneLayout.setHorizontalGroup(
            displayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPaneLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(displayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(product6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(displayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(product5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayPaneLayout.createSequentialGroup()
                            .addGroup(displayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(product1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(product2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(product3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(product4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(menuPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(15, 15, 15))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        displayPaneLayout.setVerticalGroup(
            displayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPaneLayout.createSequentialGroup()
                .addComponent(menuPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(product1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contentPaneLayout = new javax.swing.GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(displayPane, javax.swing.GroupLayout.PREFERRED_SIZE, 972, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_product_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_product_buttonActionPerformed
        AddProductUI obj = new AddProductUI();
        obj.setVisible(true);
    }//GEN-LAST:event_add_product_buttonActionPerformed
    private void profit_report_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profit_report_buttonActionPerformed
        ProfitReportUI obj = new ProfitReportUI();
        obj.setVisible(true);
    }//GEN-LAST:event_profit_report_buttonActionPerformed
    private void logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_buttonActionPerformed
        Logout obj = new Logout();
        if(logout_button.getMouseListeners() != null){
            System.exit(0);
            obj.getClass();
        }
    }//GEN-LAST:event_logout_buttonActionPerformed
    private void view_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_button1ActionPerformed
        ProductUI obj = new ProductUI();
        obj.setVisible(true);
    }//GEN-LAST:event_view_button1ActionPerformed
    private void view_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_button2ActionPerformed
        ProductUI obj = new ProductUI();
        obj.setVisible(true);
    }//GEN-LAST:event_view_button2ActionPerformed
    private void view_button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_button3ActionPerformed
        ProductUI obj = new ProductUI();
        obj.setVisible(true);
    }//GEN-LAST:event_view_button3ActionPerformed
    private void view_button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_button4ActionPerformed
        ProductUI obj = new ProductUI();
        obj.setVisible(true);
    }//GEN-LAST:event_view_button4ActionPerformed
    private void view_button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_button5ActionPerformed
        ProductUI obj = new ProductUI();
        obj.setVisible(true);
    }//GEN-LAST:event_view_button5ActionPerformed
    private void view_button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_button6ActionPerformed
        ProductUI obj = new ProductUI();
        obj.setVisible(true);
    }//GEN-LAST:event_view_button6ActionPerformed

    private void catalog_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catalog_buttonActionPerformed
        CatalogUI obj = new CatalogUI();
        obj.setVisible(true);
    }//GEN-LAST:event_catalog_buttonActionPerformed
    private void profile_buttonActionPerformed(ActionEvent evt){
        ProfileUI obj = new ProfileUI();
        obj.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellersPanelUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellersPanelUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellersPanelUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellersPanelUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellersPanelUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_product_button;
    private javax.swing.JButton catalog_button;
    private javax.swing.JPanel contentPane;
    private javax.swing.JLabel cost1;
    private javax.swing.JLabel cost2;
    private javax.swing.JLabel cost3;
    private javax.swing.JLabel cost4;
    private javax.swing.JLabel cost5;
    private javax.swing.JLabel cost6;
    private javax.swing.JPanel displayPane;
    private javax.swing.JPanel headerPane;
    private javax.swing.JLabel icon;
    private javax.swing.JButton logout_button;
    private javax.swing.JPanel menuPane;
    private javax.swing.JPanel product1;
    private javax.swing.JPanel product2;
    private javax.swing.JPanel product3;
    private javax.swing.JPanel product4;
    private javax.swing.JPanel product5;
    private javax.swing.JPanel product6;
    private javax.swing.JLabel product_name1;
    private javax.swing.JLabel product_name2;
    private javax.swing.JLabel product_name3;
    private javax.swing.JLabel product_name4;
    private javax.swing.JLabel product_name5;
    private javax.swing.JLabel product_name6;
    private javax.swing.JButton profile_button;
    private javax.swing.JButton profit_report_button;
    private javax.swing.JLabel seller_header;
    private javax.swing.JButton view_button1;
    private javax.swing.JButton view_button2;
    private javax.swing.JButton view_button3;
    private javax.swing.JButton view_button4;
    private javax.swing.JButton view_button5;
    private javax.swing.JButton view_button6;
    // End of variables declaration//GEN-END:variables
}
