package pages_Jeff_Admin;

import javax.swing.*;
import java.awt.event.*;
import java.util.List;

import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.border.Border;

import datebase_jon.ShopletSystemManager;
import datebase_jon.User;
import net.miginfocom.swing.MigLayout;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;

public class ActiveSellersUI extends JFrame implements ActionListener{

    /**
     * Creates new form ActiveSellersUI
     */
    public ActiveSellersUI() {
    	setTitle("Admin Panel - Active Sellers");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPane = new javax.swing.JPanel();
        menuPane = new javax.swing.JPanel();
        active_sellersPane = new javax.swing.JPanel();

        contentPane.setBackground(new Color(240, 240, 240));

        menuPane.setBackground(new Color(240, 240, 240));
        back_button = new javax.swing.JButton();
        back_button.setForeground(new Color(255, 255, 255));
        
                back_button.setBackground(new java.awt.Color(102, 102, 102));
                back_button.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
                back_button.setText("Close");
                back_button.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        back_buttonActionPerformed(evt);
                    }
                });

        javax.swing.GroupLayout menuPaneLayout = new javax.swing.GroupLayout(menuPane);
        menuPaneLayout.setHorizontalGroup(
        	menuPaneLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(menuPaneLayout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(back_button, GroupLayout.PREFERRED_SIZE, 111, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(776, Short.MAX_VALUE))
        );
        menuPaneLayout.setVerticalGroup(
        	menuPaneLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(menuPaneLayout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(back_button, GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        			.addContainerGap())
        );
        menuPane.setLayout(menuPaneLayout);

        active_sellersPane.setBackground(new Color(240, 240, 240));

        javax.swing.GroupLayout contentPaneLayout = new javax.swing.GroupLayout(contentPane);
        contentPaneLayout.setHorizontalGroup(
        	contentPaneLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(contentPaneLayout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(contentPaneLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(active_sellersPane, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addGroup(contentPaneLayout.createSequentialGroup()
        					.addComponent(menuPane, GroupLayout.PREFERRED_SIZE, 897, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap())))
        );
        contentPaneLayout.setVerticalGroup(
        	contentPaneLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(contentPaneLayout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(menuPane, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
        			.addComponent(active_sellersPane, GroupLayout.PREFERRED_SIZE, 547, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        active_sellersPane.setLayout(new BoxLayout(active_sellersPane, BoxLayout.X_AXIS));
        contentPane.setLayout(contentPaneLayout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        
        active_sellersPane.setLayout(new BoxLayout(active_sellersPane, BoxLayout.Y_AXIS));
        
        //Active Users
        List<User> pendingSellers = ShopletSystemManager.getInstance().grab_sellers(true);
        
        for (int i = 0; i < pendingSellers.size(); i++)
        {
        	active_sellersPane.add(addActiveSeller(pendingSellers.get(i).firstname, pendingSellers.get(i).lastname, pendingSellers.get(i).user_id), "span, growx");
        }

        pack();
    }// </editor-fold>//GEN-END:initComponents
        private void back_buttonActionPerformed(ActionEvent evt){
        this.setVisible(false);
    }
        
        /**
         * Creates a Pending User UI component
         * @param firstName First name of user
         * @param lastName Last name of user
         * @param user_id User's id
         * @return A JPanel element to approve or deny a user
         */
        public JPanel addActiveSeller(String firstName, String lastName, Integer user_id)
        {    	
            // Convert price to 2 decimal places
            Border border = BorderFactory.createLineBorder(Color.black);

            // Build product entry
            JPanel newProductPanel = new JPanel(new MigLayout("", "[][]push[][]15", "[]"));
            newProductPanel.setPreferredSize(new Dimension(1000, 60));
            newProductPanel.setMaximumSize(new Dimension(1000, 60));
            newProductPanel.setBackground(Color.white);
            
            JLabel productLabel = new JLabel(firstName + " " + lastName);
            productLabel.setFont(new Font("Arial", Font.PLAIN, 28));
            productLabel.setMaximumSize(new Dimension(200, 100));
            
            newProductPanel.add(productLabel);
            newProductPanel.add(new JLabel("Account Type: Seller")).setFont(new Font("Arial", Font.PLAIN, 16));
            
            JButton productsBtn = new JButton("Products");

            newProductPanel.add(productsBtn);
            
            productsBtn.addActionListener(new ActionListener() {
            	public void actionPerformed(ActionEvent e) {
            		SellerProductUI newSellerUI = new SellerProductUI(ShopletSystemManager.getInstance().grab_user_info(user_id));
            		newSellerUI.setVisible(true);
            	}
            });
            
            newProductPanel.setBorder(border);

            // Return the product panel
            return newProductPanel;
        }
        
        
       public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActiveSellersUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActiveSellersUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActiveSellersUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActiveSellersUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActiveSellersUI().setVisible(true);
            }
        });
    }
    private javax.swing.JPanel active_sellersPane;
    private javax.swing.JButton back_button;
    private javax.swing.JPanel contentPane;
    private javax.swing.JPanel menuPane;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        
        
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
