package pages_Jeff_Admin;

import javax.swing.*;

//import java.awt.Window;
import java.awt.event.*;
import java.util.List;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;

import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.border.Border;

import datebase_jon.Product;
import datebase_jon.Review;
import datebase_jon.ShopletSystemManager;
import datebase_jon.User;
import net.miginfocom.swing.MigLayout;
import pages_Jeff_Seller.ProductUI;
import pages_kelvin.Cart;

import java.awt.FlowLayout;

/**
 * Admin Panel UI class
 * @author Kelvin Dhoman
 *
 */
public class AdminPanelUI extends JFrame {

    /**
     * Creates new form AdminPanelUI
     */
    public AdminPanelUI() {
    	setTitle("Admin Panel Dashboard");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        contentPane = new javax.swing.JPanel();
        logoPane = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        head_Administrator = new javax.swing.JLabel();
        head_Dashboard = new javax.swing.JLabel();
        logout_button = new javax.swing.JButton();
        logout_button.setForeground(new Color(255, 255, 255));
        pending_sellersPane = new javax.swing.JPanel();
        menuPane = new javax.swing.JPanel();
        create_new_user = new javax.swing.JButton();
        create_new_user.setForeground(new Color(255, 255, 255));
        active_sellers = new javax.swing.JButton();
        active_sellers.setForeground(new Color(255, 255, 255));
        orders = new javax.swing.JButton();
        orders.setForeground(new Color(255, 255, 255));
        pending_sellers = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contentPane.setBackground(new Color(240, 240, 240));

        logoPane.setBackground(new Color(240, 240, 240));

        logo.setIcon(new ImageIcon(AdminPanelUI.class.getResource("/pages_Jeff_Seller/icon/logo1.png"))); // NOI18N

        head_Administrator.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        head_Administrator.setForeground(new java.awt.Color(204, 0, 51));
        head_Administrator.setText("Administrator");

        head_Dashboard.setBackground(new java.awt.Color(255, 255, 255));
        head_Dashboard.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        head_Dashboard.setText("Dashboard (Pending Sellers)");

        logout_button.setBackground(new java.awt.Color(102, 102, 102));
        logout_button.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        logout_button.setText("Logout");
        logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout logoPaneLayout = new javax.swing.GroupLayout(logoPane);
        logoPaneLayout.setHorizontalGroup(
        	logoPaneLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(logoPaneLayout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(logo)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(head_Administrator)
        			.addGap(68)
        			.addComponent(head_Dashboard, GroupLayout.PREFERRED_SIZE, 269, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
        			.addComponent(logout_button, GroupLayout.PREFERRED_SIZE, 93, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        logoPaneLayout.setVerticalGroup(
        	logoPaneLayout.createParallelGroup(Alignment.LEADING)
        		.addComponent(logo)
        		.addComponent(logout_button, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
        		.addGroup(logoPaneLayout.createSequentialGroup()
        			.addGap(16)
        			.addGroup(logoPaneLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(head_Administrator, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE)
        				.addComponent(head_Dashboard, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE)))
        );
        logoPane.setLayout(logoPaneLayout);

        pending_sellersPane.setBackground(new Color(240, 240, 240));
        pending_sellersPane.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                pending_sellersPaneAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        menuPane.setBackground(new Color(240, 240, 240));

        create_new_user.setBackground(new java.awt.Color(102, 102, 102));
        create_new_user.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        create_new_user.setText("Create New User");
        create_new_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_new_userActionPerformed(evt);
            }
        });

        active_sellers.setBackground(new java.awt.Color(102, 102, 102));
        active_sellers.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        active_sellers.setText("Active Sellers");
        active_sellers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                active_sellersActionPerformed(evt);
            }
        });

        orders.setBackground(new java.awt.Color(102, 102, 102));
        orders.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        orders.setText("Orders");
        orders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPaneLayout = new javax.swing.GroupLayout(menuPane);
        menuPaneLayout.setHorizontalGroup(
        	menuPaneLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(menuPaneLayout.createSequentialGroup()
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addComponent(create_new_user, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE)
        			.addGap(132)
        			.addComponent(active_sellers, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE)
        			.addGap(136)
        			.addComponent(orders, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE))
        );
        menuPaneLayout.setVerticalGroup(
        	menuPaneLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(menuPaneLayout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(menuPaneLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(menuPaneLayout.createParallelGroup(Alignment.LEADING, false)
        					.addComponent(create_new_user, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(orders, GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
        				.addComponent(active_sellers, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        			.addContainerGap())
        );
        menuPane.setLayout(menuPaneLayout);

        pending_sellers.setBackground(new Color(240, 240, 240));

        javax.swing.GroupLayout pending_sellersPaneLayout = new javax.swing.GroupLayout(pending_sellersPane);
        pending_sellersPaneLayout.setHorizontalGroup(
        	pending_sellersPaneLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(pending_sellersPaneLayout.createSequentialGroup()
        			.addGap(47)
        			.addComponent(menuPane, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(38, Short.MAX_VALUE))
        		.addComponent(pending_sellers, GroupLayout.DEFAULT_SIZE, 843, Short.MAX_VALUE)
        );
        pending_sellersPaneLayout.setVerticalGroup(
        	pending_sellersPaneLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(pending_sellersPaneLayout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(menuPane, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(24)
        			.addComponent(pending_sellers, GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        			.addContainerGap())
        );
        pending_sellers.setLayout(new BoxLayout(pending_sellers, BoxLayout.X_AXIS));
        pending_sellersPane.setLayout(pending_sellersPaneLayout);

        javax.swing.GroupLayout contentPaneLayout = new javax.swing.GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(pending_sellersPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(pending_sellersPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        
        pending_sellers.setLayout(new BoxLayout(pending_sellers, BoxLayout.Y_AXIS));
        
        //Pending Users
        List<User> pendingSellers = ShopletSystemManager.getInstance().grab_sellers(false);
        
        for (int i = 0; i < pendingSellers.size(); i++)
        {
        	pending_sellers.add(addPendingSeller(pendingSellers.get(i).firstname, pendingSellers.get(i).lastname, pendingSellers.get(i).user_id), "span, growx");
        }

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pending_sellersPaneAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_pending_sellersPaneAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_pending_sellersPaneAncestorAdded

//GEN-FIRST:event_ordersActionPerformed
 
//GEN-LAST:event_ordersActionPerformed

    private void active_sellersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_active_sellersActionPerformed
        ActiveSellersUI obj = new ActiveSellersUI();
        obj.setVisible(true);
    }//GEN-LAST:event_active_sellersActionPerformed

    private void create_new_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_new_userActionPerformed
        CreateNewUserUI obj = new CreateNewUserUI();
        obj.setVisible(true);
    }//GEN-LAST:event_create_new_userActionPerformed
    private void ordersActionPerformed(ActionEvent evt){
        OrdersUI obj = new OrdersUI();
        obj.setVisible(true);
    }
    private void logout_buttonActionPerformed(ActionEvent evt){
        Logout obj = new Logout();
        if(logout_button.getMouseListeners() != null){
            System.exit(0);
            obj.getClass();
            //AdminPanelUI.dispose();
        }
    }

/* *//* 
    private void displayPaneAncestorAdded(javax.swing.event.AncestorEvent evt) {                                          
        PendingSellersUI obj = new PendingSellersUI();
        obj.setVisible(true);
    }
*/
  
    /**
     * Creates a Pending User UI component
     * @param firstName First name of user
     * @param lastName Last name of user
     * @param user_id User's id
     * @return A JPanel element to approve or deny a user
     */
    public JPanel addPendingSeller(String firstName, String lastName, Integer user_id)
    {    	
        // Convert price to 2 decimal places
        Border border = BorderFactory.createLineBorder(Color.black);

        // Build product entry
        JPanel newProductPanel = new JPanel(new MigLayout("", "[][]push[][]15", "[]"));
        newProductPanel.setPreferredSize(new Dimension(1000, 60));
        newProductPanel.setMaximumSize(new Dimension(1000, 60));
        newProductPanel.setBackground(Color.white);
        
        JLabel productLabel = new JLabel(firstName + " " + lastName);
        productLabel.setFont(new Font("Arial", Font.PLAIN, 28));
        productLabel.setMaximumSize(new Dimension(200, 100));
        
        newProductPanel.add(productLabel);
        newProductPanel.add(new JLabel("Account Type: Seller")).setFont(new Font("Arial", Font.PLAIN, 16));
        
        JButton approveBtn = new JButton("Approve");
        JButton denyBtn = new JButton("Deny");

        newProductPanel.add(approveBtn);
        newProductPanel.add(denyBtn);
        
        approveBtn.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		ShopletSystemManager.getInstance().edit_user(user_id, null, null, null, null, null,  true);
        		JOptionPane.showMessageDialog(null, "User has been approved.", "Shoplet", JOptionPane.INFORMATION_MESSAGE);
        		refreshPendingUserList();
        	}
        });
        
        denyBtn.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		ShopletSystemManager.getInstance().edit_user(user_id, null, null, null, null, "buyer", false);
        		JOptionPane.showMessageDialog(null, "User has been denied.", "Shoplet", JOptionPane.INFORMATION_MESSAGE);
        		refreshPendingUserList();
        	}
        });
        
        newProductPanel.setBorder(border);

        // Return the product panel
        return newProductPanel;
    }
    
    /**
     * Refreshes Pending User list UI
     */
    public void refreshPendingUserList()
    {
    	pending_sellers.removeAll();
		
		//Pending Sellers
		 List<User> pendingSellers = ShopletSystemManager.getInstance().grab_sellers(false);
	     
	     for (int i = 0; i < pendingSellers.size(); i++)
	     {
	     	pending_sellers.add(addPendingSeller(pendingSellers.get(i).firstname, pendingSellers.get(i).lastname, pendingSellers.get(i).user_id), "span, growx");
	     }
			
       pending_sellers.revalidate();
       pending_sellers.repaint();	
    }

    

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanelUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanelUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanelUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanelUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanelUI().setVisible(true);   
            }
        });
        
        //AdminPanelUI obj = new AdminPanelUI();
        //JFrame frame = new AdminPanelUI();
    }
    private javax.swing.JButton active_sellers;
    private javax.swing.JPanel contentPane;
    private javax.swing.JButton create_new_user;
    private javax.swing.JLabel head_Administrator;
    private javax.swing.JLabel head_Dashboard;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel logoPane;
    private javax.swing.JButton logout_button;
    private javax.swing.JPanel menuPane;
    private javax.swing.JButton orders;
    private javax.swing.JPanel pending_sellers;
    private javax.swing.JPanel pending_sellersPane;
    // End of variables declaration//GEN-END:variables
}
