package pages_Jeff_Admin;

import javax.swing.*;

import datebase_jon.ShopletSystemManager;

import java.awt.event.*;
import java.awt.Color;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 * Creates a new user class UI
 * @author Kelvin Dhoman
 *
 */
public class CreateNewUserUI extends JFrame implements ActionListener{

    /**
     * Creates new form CreateNewUserUI
     */
    public CreateNewUserUI() {
    	setTitle("Admin - Create User");
    	getContentPane().setBackground(new Color(240, 240, 240));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPane = new javax.swing.JPanel();
        logoPane = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        header_message = new javax.swing.JLabel();
        inforPane = new javax.swing.JPanel();
        account_type = new javax.swing.JLabel();
        account_type.setBounds(31, 11, 132, 32);
        email = new javax.swing.JLabel();
        email.setBounds(31, 61, 126, 32);
        username = new javax.swing.JLabel();
        username.setBounds(31, 191, 126, 31);
        password = new javax.swing.JLabel();
        password.setBounds(31, 233, 126, 32);
        confirm_password = new javax.swing.JLabel();
        confirm_password.setBounds(31, 277, 126, 30);
        account_typeCombo = new javax.swing.JComboBox<>();
        account_typeCombo.setBounds(181, 16, 218, 22);
        email_TextField = new javax.swing.JTextField();
        email_TextField.setBounds(181, 69, 218, 16);
        username_TextField = new javax.swing.JTextField();
        username_TextField.setBounds(179, 198, 218, 16);
        passwor_PasswordField = new javax.swing.JPasswordField();
        passwor_PasswordField.setBounds(179, 241, 218, 16);
        comfirm_passwor_PasswordField = new javax.swing.JPasswordField();
        comfirm_passwor_PasswordField.setBounds(179, 284, 218, 16);
        create = new javax.swing.JButton();
        create.setBounds(179, 324, 100, 32);
        cancel = new javax.swing.JButton();
        cancel.setBounds(297, 324, 100, 32);

        contentPane.setBackground(new Color(240, 240, 240));

        logoPane.setBackground(new Color(240, 240, 240));

        logo.setIcon(new ImageIcon(CreateNewUserUI.class.getResource("/pages_Jeff_Admin/logo1.png"))); // NOI18N

        header_message.setBackground(new java.awt.Color(255, 255, 255));
        header_message.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        header_message.setText("Create a SHOPLET Account");

        javax.swing.GroupLayout logoPaneLayout = new javax.swing.GroupLayout(logoPane);
        logoPane.setLayout(logoPaneLayout);
        logoPaneLayout.setHorizontalGroup(
            logoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPaneLayout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(logo)
                .addGap(26, 26, 26)
                .addComponent(header_message)
                .addGap(76, 76, 76))
        );
        logoPaneLayout.setVerticalGroup(
            logoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(header_message, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(logoPaneLayout.createSequentialGroup()
                .addComponent(logo)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        inforPane.setBackground(new Color(240, 240, 240));

        account_type.setText("Account Type :");

        email.setText("Email :");

        username.setText("Username :");

        password.setText("Password :");

        confirm_password.setText("Confirm Password :");

        account_typeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buyer", "Seller", "Admin" }));
        account_typeCombo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        email_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        username_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        passwor_PasswordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        comfirm_passwor_PasswordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        create.setBackground(new java.awt.Color(153, 204, 255));
        create.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        create.setText("Create");
        create.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        cancel.setBackground(new java.awt.Color(153, 204, 255));
        cancel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        cancel.setText("Cancel");
        cancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentPaneLayout = new javax.swing.GroupLayout(contentPane);
        contentPaneLayout.setHorizontalGroup(
        	contentPaneLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(contentPaneLayout.createSequentialGroup()
        			.addGroup(contentPaneLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(contentPaneLayout.createSequentialGroup()
        					.addGap(53)
        					.addComponent(logoPane, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(contentPaneLayout.createSequentialGroup()
        					.addGap(115)
        					.addComponent(inforPane, GroupLayout.PREFERRED_SIZE, 557, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(79, Short.MAX_VALUE))
        );
        contentPaneLayout.setVerticalGroup(
        	contentPaneLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(contentPaneLayout.createSequentialGroup()
        			.addGap(37)
        			.addComponent(logoPane, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(inforPane, GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
        			.addContainerGap())
        );
        inforPane.setLayout(null);
        inforPane.add(confirm_password);
        inforPane.add(password);
        inforPane.add(username);
        inforPane.add(email);
        inforPane.add(account_type);
        inforPane.add(account_typeCombo);
        inforPane.add(email_TextField);
        inforPane.add(username_TextField);
        inforPane.add(passwor_PasswordField);
        inforPane.add(comfirm_passwor_PasswordField);
        inforPane.add(create);
        inforPane.add(cancel);
        
        inputLastName = new JTextField();
        inputLastName.setBounds(179, 150, 218, 20);
        inforPane.add(inputLastName);
        inputLastName.setColumns(10);
        
        inputFirstName = new JTextField();
        inputFirstName.setColumns(10);
        inputFirstName.setBounds(181, 108, 218, 20);
        inforPane.add(inputFirstName);
        
        firstNameLbl = new JLabel();
        firstNameLbl.setText("First Name:");
        firstNameLbl.setBounds(33, 104, 126, 32);
        inforPane.add(firstNameLbl);
        
        lastNameLbl = new JLabel();
        lastNameLbl.setText("Last Name:");
        lastNameLbl.setBounds(31, 148, 126, 32);
        inforPane.add(lastNameLbl);
        contentPane.setLayout(contentPaneLayout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contentPane, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(ActionEvent evt){
    	this.setVisible(false);
    }

    private void createActionPerformed(ActionEvent evt){
        if (email_TextField.getText().isEmpty() || inputFirstName.getText().isEmpty() || inputLastName.getText().isEmpty() || username_TextField.getText().isEmpty() 
        		|| passwor_PasswordField.getText().isEmpty() || comfirm_passwor_PasswordField.getText().isEmpty())
        {
    		JOptionPane.showMessageDialog(null, "One or more fields are empty.", "Shoplet", JOptionPane.ERROR_MESSAGE);
    		return;
        }
    	else if (!(passwor_PasswordField.getText().equals(comfirm_passwor_PasswordField.getText()))) {
    		JOptionPane.showMessageDialog(null, "Password fields do not match.", "Shoplet", JOptionPane.ERROR_MESSAGE);
    		return;
        }
        else
        {
        	ShopletSystemManager.getInstance().add_user(inputFirstName.getText(), inputLastName.getText(), email_TextField.getText(), passwor_PasswordField.getText(), account_typeCombo.getSelectedItem().toString(), true);
    		JOptionPane.showMessageDialog(null, "User successfully created.", "Shoplet", JOptionPane.INFORMATION_MESSAGE);
    		this.setVisible(false);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateNewUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateNewUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateNewUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateNewUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateNewUserUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel account_type;
    private javax.swing.JComboBox<String> account_typeCombo;
    private javax.swing.JButton cancel;
    private javax.swing.JPasswordField comfirm_passwor_PasswordField;
    private javax.swing.JLabel confirm_password;
    private javax.swing.JPanel contentPane;
    private javax.swing.JButton create;
    private javax.swing.JLabel email;
    private javax.swing.JTextField email_TextField;
    private javax.swing.JLabel header_message;
    private javax.swing.JPanel inforPane;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel logoPane;
    private javax.swing.JPasswordField passwor_PasswordField;
    private javax.swing.JLabel password;
    private javax.swing.JLabel username;
    private javax.swing.JTextField username_TextField;
    private JTextField inputLastName;
    private JTextField inputFirstName;
    private JLabel firstNameLbl;
    private JLabel lastNameLbl;
    // End of variables declaration//GEN-END:variables
    @Override
    public void actionPerformed(ActionEvent e) {
        // TODO Auto-generated method stub
        
    }
}
