package pages_Jeff_Admin;

import javax.swing.*;
//import javax.swing.event.AncestorEvent;
//import javax.swing.event.AncestorListener;

import java.awt.event.*;
import java.awt.Color;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

public class PendingSellersUI extends JFrame implements ActionListener{
    /**
     * Creates new form PendingSellersUI
     */
    public PendingSellersUI() {
    	setTitle("Admin - Pending Users");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPane = new javax.swing.JPanel();
        menuPane = new javax.swing.JPanel();
        back_button = new javax.swing.JButton();
        back_button.setForeground(new Color(255, 255, 255));
        pending_sellersPane = new javax.swing.JPanel();
        pending_sellers1 = new javax.swing.JPanel();
        fname_lname1 = new javax.swing.JLabel();
        account_type1 = new javax.swing.JLabel();
        accept1 = new javax.swing.JButton();
        accept1.setForeground(new Color(255, 255, 255));
        decline1 = new javax.swing.JButton();
        decline1.setForeground(new Color(255, 255, 255));
        pending_sellers2 = new javax.swing.JPanel();
        fname_lname2 = new javax.swing.JLabel();
        account_type2 = new javax.swing.JLabel();
        accept2 = new javax.swing.JButton();
        accept2.setForeground(new Color(255, 255, 255));
        decline2 = new javax.swing.JButton();
        decline2.setForeground(new Color(255, 255, 255));
        pending_sellers3 = new javax.swing.JPanel();
        fname_lname3 = new javax.swing.JLabel();
        account_type3 = new javax.swing.JLabel();
        accept3 = new javax.swing.JButton();
        accept3.setForeground(new Color(255, 255, 255));
        decline3 = new javax.swing.JButton();
        decline3.setForeground(new Color(255, 255, 255));
        pending_sellers4 = new javax.swing.JPanel();
        fname_lname4 = new javax.swing.JLabel();
        account_type4 = new javax.swing.JLabel();
        accept4 = new javax.swing.JButton();
        accept4.setForeground(new Color(255, 255, 255));
        decline4 = new javax.swing.JButton();
        decline4.setForeground(new Color(255, 255, 255));
        pending_sellers5 = new javax.swing.JPanel();
        fname_lname5 = new javax.swing.JLabel();
        account_type5 = new javax.swing.JLabel();
        accept5 = new javax.swing.JButton();
        accept5.setForeground(new Color(255, 255, 255));
        decline5 = new javax.swing.JButton();
        decline5.setForeground(new Color(255, 255, 255));
        pending_sellers6 = new javax.swing.JPanel();
        fname_lname6 = new javax.swing.JLabel();
        account_type6 = new javax.swing.JLabel();
        accept6 = new javax.swing.JButton();
        accept6.setForeground(new Color(255, 255, 255));
        decline6 = new javax.swing.JButton();
        decline6.setForeground(new Color(255, 255, 255));
        pending_sellers7 = new javax.swing.JPanel();
        fname_lname7 = new javax.swing.JLabel();
        account_type7 = new javax.swing.JLabel();
        accept7 = new javax.swing.JButton();
        accept7.setForeground(new Color(255, 255, 255));
        decline7 = new javax.swing.JButton();
        decline7.setForeground(new Color(255, 255, 255));
        pending_sellers8 = new javax.swing.JPanel();
        fname_lname8 = new javax.swing.JLabel();
        account_type8 = new javax.swing.JLabel();
        accept8 = new javax.swing.JButton();
        accept8.setForeground(new Color(255, 255, 255));
        decline8 = new javax.swing.JButton();
        decline8.setForeground(new Color(255, 255, 255));

        //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contentPane.setBackground(new Color(240, 240, 240));

        menuPane.setBackground(new Color(240, 240, 240));

        back_button.setBackground(new java.awt.Color(102, 102, 102));
        back_button.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        back_button.setText("Close");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPaneLayout = new javax.swing.GroupLayout(menuPane);
        menuPaneLayout.setHorizontalGroup(
        	menuPaneLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, menuPaneLayout.createSequentialGroup()
        			.addGap(21)
        			.addComponent(back_button, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(826, Short.MAX_VALUE))
        );
        menuPaneLayout.setVerticalGroup(
        	menuPaneLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(menuPaneLayout.createSequentialGroup()
        			.addGap(11)
        			.addComponent(back_button, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE))
        );
        menuPane.setLayout(menuPaneLayout);

        pending_sellersPane.setBackground(new Color(240, 240, 240));

        pending_sellers1.setBackground(new java.awt.Color(255, 255, 255));
        pending_sellers1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fname_lname1.setText("F. Name L. Name");

        account_type1.setText("Account Type: Seller");

        accept1.setBackground(new java.awt.Color(102, 102, 102));
        accept1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        accept1.setText("Accept");
        accept1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accept1ActionPerformed(evt);
            }
        });

        decline1.setBackground(new java.awt.Color(102, 102, 102));
        decline1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        decline1.setText("Decline");
        decline1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decline1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pending_sellers1Layout = new javax.swing.GroupLayout(pending_sellers1);
        pending_sellers1.setLayout(pending_sellers1Layout);
        pending_sellers1Layout.setHorizontalGroup(
            pending_sellers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pending_sellers1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fname_lname1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(account_type1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(accept1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(decline1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pending_sellers1Layout.setVerticalGroup(
            pending_sellers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pending_sellers1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pending_sellers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(account_type1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fname_lname1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accept1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(decline1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pending_sellers2.setBackground(new java.awt.Color(255, 255, 255));
        pending_sellers2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fname_lname2.setText("F. Name L. Name");

        account_type2.setText("Account Type: Seller");

        accept2.setBackground(new java.awt.Color(102, 102, 102));
        accept2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        accept2.setText("Accept");
        accept2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accept2ActionPerformed(evt);
            }
        });

        decline2.setBackground(new java.awt.Color(102, 102, 102));
        decline2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        decline2.setText("Decline");
        decline2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decline2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pending_sellers2Layout = new javax.swing.GroupLayout(pending_sellers2);
        pending_sellers2.setLayout(pending_sellers2Layout);
        pending_sellers2Layout.setHorizontalGroup(
            pending_sellers2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pending_sellers2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fname_lname2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(account_type2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 327, Short.MAX_VALUE)
                .addComponent(accept2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(decline2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pending_sellers2Layout.setVerticalGroup(
            pending_sellers2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pending_sellers2Layout.createSequentialGroup()
                .addGroup(pending_sellers2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(account_type2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pending_sellers2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pending_sellers2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pending_sellers2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(decline2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(accept2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fname_lname2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        pending_sellers3.setBackground(new java.awt.Color(255, 255, 255));
        pending_sellers3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fname_lname3.setText("F. Name L. Name");

        account_type3.setText("Account Type: Seller");

        accept3.setBackground(new java.awt.Color(102, 102, 102));
        accept3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        accept3.setText("Accept");
        accept3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accept3ActionPerformed(evt);
            }
        });

        decline3.setBackground(new java.awt.Color(102, 102, 102));
        decline3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        decline3.setText("Decline");
        decline3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decline3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pending_sellers3Layout = new javax.swing.GroupLayout(pending_sellers3);
        pending_sellers3.setLayout(pending_sellers3Layout);
        pending_sellers3Layout.setHorizontalGroup(
            pending_sellers3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pending_sellers3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fname_lname3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(account_type3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(accept3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(decline3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pending_sellers3Layout.setVerticalGroup(
            pending_sellers3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pending_sellers3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pending_sellers3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fname_lname3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(account_type3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pending_sellers3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(accept3, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                        .addComponent(decline3, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pending_sellers4.setBackground(new java.awt.Color(255, 255, 255));
        pending_sellers4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fname_lname4.setText("F. Name L. Name");

        account_type4.setText("Account Type: Seller");

        accept4.setBackground(new java.awt.Color(102, 102, 102));
        accept4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        accept4.setText("Accept");
        accept4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accept4ActionPerformed(evt);
            }
        });

        decline4.setBackground(new java.awt.Color(102, 102, 102));
        decline4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        decline4.setText("Decline");
        decline4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decline4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pending_sellers4Layout = new javax.swing.GroupLayout(pending_sellers4);
        pending_sellers4.setLayout(pending_sellers4Layout);
        pending_sellers4Layout.setHorizontalGroup(
            pending_sellers4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pending_sellers4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fname_lname4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(account_type4, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(accept4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(decline4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pending_sellers4Layout.setVerticalGroup(
            pending_sellers4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pending_sellers4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pending_sellers4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fname_lname4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(account_type4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pending_sellers4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(accept4, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                        .addComponent(decline4, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pending_sellers5.setBackground(new java.awt.Color(255, 255, 255));
        pending_sellers5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fname_lname5.setText("F. Name L. Name");

        account_type5.setText("Account Type: Seller");

        accept5.setBackground(new java.awt.Color(102, 102, 102));
        accept5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        accept5.setText("Accept");
        accept5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accept5ActionPerformed(evt);
            }
        });

        decline5.setBackground(new java.awt.Color(102, 102, 102));
        decline5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        decline5.setText("Decline");
        decline5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decline5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pending_sellers5Layout = new javax.swing.GroupLayout(pending_sellers5);
        pending_sellers5.setLayout(pending_sellers5Layout);
        pending_sellers5Layout.setHorizontalGroup(
            pending_sellers5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pending_sellers5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fname_lname5, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(account_type5, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(accept5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(decline5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pending_sellers5Layout.setVerticalGroup(
            pending_sellers5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pending_sellers5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pending_sellers5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fname_lname5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(account_type5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pending_sellers5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(accept5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(decline5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pending_sellers6.setBackground(new java.awt.Color(255, 255, 255));
        pending_sellers6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fname_lname6.setText("F. Name L. Name");

        account_type6.setText("Account Type: Seller");

        accept6.setBackground(new java.awt.Color(102, 102, 102));
        accept6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        accept6.setText("Accept");
        accept6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accept6ActionPerformed(evt);
            }
        });

        decline6.setBackground(new java.awt.Color(102, 102, 102));
        decline6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        decline6.setText("Decline");
        decline6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decline6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pending_sellers6Layout = new javax.swing.GroupLayout(pending_sellers6);
        pending_sellers6.setLayout(pending_sellers6Layout);
        pending_sellers6Layout.setHorizontalGroup(
            pending_sellers6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pending_sellers6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fname_lname6, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(account_type6, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(accept6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(decline6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pending_sellers6Layout.setVerticalGroup(
            pending_sellers6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pending_sellers6Layout.createSequentialGroup()
                .addGroup(pending_sellers6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(account_type6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pending_sellers6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pending_sellers6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fname_lname6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pending_sellers6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(accept6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(decline6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        pending_sellers7.setBackground(new java.awt.Color(255, 255, 255));
        pending_sellers7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fname_lname7.setText("F. Name L. Name3");

        account_type7.setText("Account Type: Seller");

        accept7.setBackground(new java.awt.Color(102, 102, 102));
        accept7.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        accept7.setText("Accept");
        accept7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accept7ActionPerformed(evt);
            }
        });

        decline7.setBackground(new java.awt.Color(102, 102, 102));
        decline7.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        decline7.setText("Decline");
        decline7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decline7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pending_sellers7Layout = new javax.swing.GroupLayout(pending_sellers7);
        pending_sellers7.setLayout(pending_sellers7Layout);
        pending_sellers7Layout.setHorizontalGroup(
            pending_sellers7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pending_sellers7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fname_lname7, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(account_type7, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(accept7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(decline7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pending_sellers7Layout.setVerticalGroup(
            pending_sellers7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pending_sellers7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pending_sellers7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fname_lname7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(account_type7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pending_sellers7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(accept7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(decline7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pending_sellers8.setBackground(new java.awt.Color(255, 255, 255));
        pending_sellers8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fname_lname8.setText("F. Name L. Name");

        account_type8.setText("Account Type: Seller");

        accept8.setBackground(new java.awt.Color(102, 102, 102));
        accept8.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        accept8.setText("Accept");
        accept8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accept8ActionPerformed(evt);
            }
        });

        decline8.setBackground(new java.awt.Color(102, 102, 102));
        decline8.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        decline8.setText("Decline");
        decline8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decline8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pending_sellers8Layout = new javax.swing.GroupLayout(pending_sellers8);
        pending_sellers8.setLayout(pending_sellers8Layout);
        pending_sellers8Layout.setHorizontalGroup(
            pending_sellers8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pending_sellers8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fname_lname8, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(account_type8, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(accept8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(decline8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pending_sellers8Layout.setVerticalGroup(
            pending_sellers8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pending_sellers8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pending_sellers8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fname_lname8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(account_type8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pending_sellers8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(accept8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(decline8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout pending_sellersPaneLayout = new javax.swing.GroupLayout(pending_sellersPane);
        pending_sellersPane.setLayout(pending_sellersPaneLayout);
        pending_sellersPaneLayout.setHorizontalGroup(
            pending_sellersPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pending_sellersPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pending_sellersPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pending_sellers2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pending_sellers1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pending_sellers3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pending_sellers4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pending_sellers5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pending_sellers6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pending_sellers7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pending_sellers8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pending_sellersPaneLayout.setVerticalGroup(
            pending_sellersPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pending_sellersPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pending_sellers1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pending_sellers2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pending_sellers3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pending_sellers4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pending_sellers5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pending_sellers6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pending_sellers7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pending_sellers8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contentPaneLayout = new javax.swing.GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pending_sellersPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(pending_sellersPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
    	this.setVisible(false);
    }//GEN-LAST:event_back_buttonActionPerformed

    private void decline1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decline1ActionPerformed
        if(decline1.getMouseListeners() != null){
            pending_sellers1.setVisible(false);
        }
    }//GEN-LAST:event_decline1ActionPerformed

    private void decline3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decline3ActionPerformed
        if(decline3.getMouseListeners() != null){
            pending_sellers3.setVisible(false);
        }
    }//GEN-LAST:event_decline3ActionPerformed

    private void decline4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decline4ActionPerformed
        if(decline4.getMouseListeners() != null){
            pending_sellers4.setVisible(false);
        }
    }//GEN-LAST:event_decline4ActionPerformed

    private void decline5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decline5ActionPerformed
        if(decline5.getMouseListeners() != null){
            pending_sellers5.setVisible(false);
        }
    }//GEN-LAST:event_decline5ActionPerformed

    private void decline6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decline6ActionPerformed
        if(decline6.getMouseListeners() != null){
            pending_sellers6.setVisible(false);
        }
    }//GEN-LAST:event_decline6ActionPerformed

    private void decline7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decline7ActionPerformed
        if(decline7.getMouseListeners() != null){
            pending_sellers7.setVisible(false);
        }
    }//GEN-LAST:event_decline7ActionPerformed

    private void decline8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decline8ActionPerformed
        if(decline8.getMouseListeners() != null){
            pending_sellers8.setVisible(false);
        }
    }//GEN-LAST:event_decline8ActionPerformed

    private void accept1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accept1ActionPerformed
        if(accept1.getMouseListeners() != null){
            pending_sellers1.setVisible(false);
        }
    }//GEN-LAST:event_accept1ActionPerformed

    private void accept2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accept2ActionPerformed
        if(accept2.getMouseListeners() != null){
            pending_sellers2.setVisible(false);
        }
    }//GEN-LAST:event_accept2ActionPerformed

    private void accept3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accept3ActionPerformed
        if(accept3.getMouseListeners() != null){
            pending_sellers3.setVisible(false);
        }
    }//GEN-LAST:event_accept3ActionPerformed

    private void accept4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accept4ActionPerformed
        if(accept4.getMouseListeners() != null){
            pending_sellers4.setVisible(false);
        }
    }//GEN-LAST:event_accept4ActionPerformed

    private void accept5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accept5ActionPerformed
        if(accept5.getMouseListeners() != null){
            pending_sellers5.setVisible(false);
        }
    }//GEN-LAST:event_accept5ActionPerformed

    private void accept6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accept6ActionPerformed
        if(accept6.getMouseListeners() != null){
            pending_sellers6.setVisible(false);
        }
    }//GEN-LAST:event_accept6ActionPerformed

    private void accept7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accept7ActionPerformed
        if(accept7.getMouseListeners() != null){
            pending_sellers7.setVisible(false);
        }
    }//GEN-LAST:event_accept7ActionPerformed

    private void accept8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accept8ActionPerformed
        if(accept8.getMouseListeners() != null){
            pending_sellers8.setVisible(false);
        }
    }//GEN-LAST:event_accept8ActionPerformed
    private void  decline2ActionPerformed(ActionEvent evt){
        if(decline2.getMouseListeners() != null){
            pending_sellers2.setVisible(false);
        }
    }
/* 
    private void accept1ActionPerformed(ActionEvent evt){
        if(accept1.getMouseListeners() != null){
            //pending_sellers1.add();
        }
    }
*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PendingSellersUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PendingSellersUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PendingSellersUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PendingSellersUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PendingSellersUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accept1;
    private javax.swing.JButton accept2;
    private javax.swing.JButton accept3;
    private javax.swing.JButton accept4;
    private javax.swing.JButton accept5;
    private javax.swing.JButton accept6;
    private javax.swing.JButton accept7;
    private javax.swing.JButton accept8;
    private javax.swing.JLabel account_type1;
    private javax.swing.JLabel account_type2;
    private javax.swing.JLabel account_type3;
    private javax.swing.JLabel account_type4;
    private javax.swing.JLabel account_type5;
    private javax.swing.JLabel account_type6;
    private javax.swing.JLabel account_type7;
    private javax.swing.JLabel account_type8;
    private javax.swing.JButton back_button;
    private javax.swing.JPanel contentPane;
    private javax.swing.JButton decline1;
    private javax.swing.JButton decline2;
    private javax.swing.JButton decline3;
    private javax.swing.JButton decline4;
    private javax.swing.JButton decline5;
    private javax.swing.JButton decline6;
    private javax.swing.JButton decline7;
    private javax.swing.JButton decline8;
    private javax.swing.JLabel fname_lname1;
    private javax.swing.JLabel fname_lname2;
    private javax.swing.JLabel fname_lname3;
    private javax.swing.JLabel fname_lname4;
    private javax.swing.JLabel fname_lname5;
    private javax.swing.JLabel fname_lname6;
    private javax.swing.JLabel fname_lname7;
    private javax.swing.JLabel fname_lname8;
    private javax.swing.JPanel menuPane;
    private javax.swing.JPanel pending_sellers1;
    private javax.swing.JPanel pending_sellers2;
    private javax.swing.JPanel pending_sellers3;
    private javax.swing.JPanel pending_sellers4;
    private javax.swing.JPanel pending_sellers5;
    private javax.swing.JPanel pending_sellers6;
    private javax.swing.JPanel pending_sellers7;
    private javax.swing.JPanel pending_sellers8;
    private javax.swing.JPanel pending_sellersPane;
    // End of variables declaration//GEN-END:variables
    @Override
    public void actionPerformed(ActionEvent e) {
        // TODO Auto-generated method stub
        
    }
   
}
