/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pages_Jeff_Admin;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;

import datebase_jon.Product;
import datebase_jon.ShopletSystemManager;
import datebase_jon.User;
import net.miginfocom.swing.MigLayout;
import pages_Jeff_Seller.ProductUI;

import javax.swing.GroupLayout.Alignment;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.border.Border;
import javax.swing.BoxLayout;

/**
 *
 * @author jeffplatel
 */
public class SellerProductUI extends javax.swing.JFrame {

    /**
     * Creates new form SellerProductUI
     */
    public SellerProductUI(User user) {
    	setTitle("Seller Products");
    	this.user = user;
    	
    	addWindowListener(new WindowAdapter() {
        	@Override
        	public void windowActivated(WindowEvent e) {
        		// Update cart text button when user focuses on window.
        		System.out.println("Product list refreshed");
        		refreshProductsList();
        	}
        });
    	
        initComponents();
    }
    
    User user;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPane = new javax.swing.JPanel();
        back_button = new javax.swing.JButton();
        back_button.setForeground(new Color(255, 255, 255));
        product_listPane = new javax.swing.JPanel();

        contentPane.setBackground(new Color(240, 240, 240));

        back_button.setBackground(new java.awt.Color(102, 102, 102));
        back_button.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        back_button.setText("Close");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setVisible(false);
            }
        });

        product_listPane.setBackground(new Color(240, 240, 240));

        javax.swing.GroupLayout contentPaneLayout = new javax.swing.GroupLayout(contentPane);
        contentPaneLayout.setHorizontalGroup(
        	contentPaneLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(contentPaneLayout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(contentPaneLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(product_listPane, GroupLayout.PREFERRED_SIZE, 515, GroupLayout.PREFERRED_SIZE)
        				.addComponent(back_button, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentPaneLayout.setVerticalGroup(
        	contentPaneLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(contentPaneLayout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(back_button, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(product_listPane, GroupLayout.PREFERRED_SIZE, 416, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentPane.setLayout(contentPaneLayout);
        product_listPane.setLayout(new BoxLayout(product_listPane, BoxLayout.X_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        
        product_listPane.setLayout(new BoxLayout(product_listPane, BoxLayout.Y_AXIS));
        
        //Products
        List<Product> products = ShopletSystemManager.getInstance().get_list_of_own_products(user.user_id);
        
        for (int i = 0; i < products.size(); i++)
        {
        	product_listPane.add(ProductItem(products.get(i).product_id ,products.get(i).name, products.get(i).price, products.get(i).description), "span, growx");
        }


        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void refreshProductsList()
    {
    	product_listPane.removeAll();
		
		//Products for Sellers
        List<Product> products = ShopletSystemManager.getInstance().get_list_of_own_products(user.user_id);
	     
	     for (int i = 0; i < products.size(); i++)
	     {
	        	product_listPane.add(ProductItem(products.get(i).product_id ,products.get(i).name, products.get(i).price, products.get(i).description), "span, growx");
	     }
			
	     product_listPane.revalidate();
	     product_listPane.repaint();	
    }

    
    /**
     * The JPanel object that represents a product item entry in the product catalog.
     * @param productName The name of the product to show
     * @param productPrice The price of the product to show
     * @return
     */
    public JPanel ProductItem(Integer productId,String productName, Integer productPrice, String productDescription)
    {
    	Product product = new Product(productId, productName, productPrice, productDescription, true, 1, false);
    	
        // Convert price to 2 decimal places
        Border border = BorderFactory.createLineBorder(Color.black);

        // Build product entry
        JPanel newProductPanel = new JPanel(new MigLayout("", "[][]push[][]15", "[]"));
        newProductPanel.setPreferredSize(new Dimension(1000, 60));
        newProductPanel.setMaximumSize(new Dimension(1000, 60));
        newProductPanel.setBackground(Color.white);
        
        JLabel productLabel = new JLabel(productName);
        productLabel.setFont(new Font("Arial", Font.PLAIN, 28));
        productLabel.setMaximumSize(new Dimension(200, 100));
        
        newProductPanel.add(productLabel);
        newProductPanel.add(new JLabel("Cost: $" + productPrice)).setFont(new Font("Arial", Font.PLAIN, 16));
        
        JButton viewProduct = new JButton("View Product");
        viewProduct.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		ProductUI obj = new ProductUI(product);
            	obj.setVisible(true);
        	}
        });
        
        newProductPanel.add(viewProduct);
        newProductPanel.setBorder(border);

        // Return the product panel
        return newProductPanel;
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellerProductUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellerProductUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellerProductUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellerProductUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellerProductUI(new User()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_button;
    private javax.swing.JPanel contentPane;
    private javax.swing.JPanel product_listPane;
    // End of variables declaration//GEN-END:variables
}
