//package com.mycompany.cop4331.project_final;
package pages_Jeff;
import javax.swing.*;
import java.awt.event.*;

public class ActiveSellersUI extends JFrame implements ActionListener{

    /**
     * Creates new form ActiveSellersUI
     */
    public ActiveSellersUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPane = new javax.swing.JPanel();
        menuPane = new javax.swing.JPanel();
        create_new_user = new javax.swing.JButton();
        pending_sellers = new javax.swing.JButton();
        active_sellers = new javax.swing.JButton();
        orders = new javax.swing.JButton();
        active_sellersPane = new javax.swing.JPanel();
        active_sellers1 = new javax.swing.JPanel();
        fname_lname1 = new javax.swing.JLabel();
        account_type1 = new javax.swing.JLabel();
        product1 = new javax.swing.JButton();
        active_sellers2 = new javax.swing.JPanel();
        fname_lname2 = new javax.swing.JLabel();
        account_type2 = new javax.swing.JLabel();
        product2 = new javax.swing.JButton();
        active_sellers3 = new javax.swing.JPanel();
        fname_lname3 = new javax.swing.JLabel();
        account_type3 = new javax.swing.JLabel();
        product3 = new javax.swing.JButton();
        active_sellers4 = new javax.swing.JPanel();
        fname_lname4 = new javax.swing.JLabel();
        account_type4 = new javax.swing.JLabel();
        product4 = new javax.swing.JButton();
        active_sellers5 = new javax.swing.JPanel();
        fname_lname5 = new javax.swing.JLabel();
        account_type5 = new javax.swing.JLabel();
        product5 = new javax.swing.JButton();
        active_sellers6 = new javax.swing.JPanel();
        fname_lname6 = new javax.swing.JLabel();
        account_type6 = new javax.swing.JLabel();
        product6 = new javax.swing.JButton();
        active_sellers7 = new javax.swing.JPanel();
        fname_lname7 = new javax.swing.JLabel();
        account_type7 = new javax.swing.JLabel();
        product7 = new javax.swing.JButton();
        active_sellers8 = new javax.swing.JPanel();
        fname_lname8 = new javax.swing.JLabel();
        account_type8 = new javax.swing.JLabel();
        product8 = new javax.swing.JButton();
        back_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contentPane.setBackground(new java.awt.Color(255, 255, 255));

        menuPane.setBackground(new java.awt.Color(255, 255, 255));

        create_new_user.setBackground(new java.awt.Color(102, 102, 102));
        create_new_user.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        create_new_user.setText("Create New User");
        create_new_user.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        create_new_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_new_userActionPerformed(evt);
                }
            });

        pending_sellers.setBackground(new java.awt.Color(102, 102, 102));
        pending_sellers.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        pending_sellers.setText("Pending Sellers");
        pending_sellers.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pending_sellers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pending_sellersActionPerformed(evt);
                }
            });

        active_sellers.setBackground(new java.awt.Color(102, 102, 102));
        active_sellers.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        active_sellers.setText("Active Sellers");
        active_sellers.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        orders.setBackground(new java.awt.Color(102, 102, 102));
        orders.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        orders.setText("Orders");
        orders.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        orders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordersActionPerformed(evt);
                }
            });

        javax.swing.GroupLayout menuPaneLayout = new javax.swing.GroupLayout(menuPane);
        menuPane.setLayout(menuPaneLayout);
        menuPaneLayout.setHorizontalGroup(
            menuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPaneLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(create_new_user, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(pending_sellers, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(active_sellers, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(orders, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        menuPaneLayout.setVerticalGroup(
            menuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(create_new_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pending_sellers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(active_sellers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orders, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        active_sellersPane.setBackground(new java.awt.Color(255, 255, 255));

        active_sellers1.setBackground(new java.awt.Color(255, 255, 255));
        active_sellers1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fname_lname1.setText("F. Name L. Name");

        account_type1.setText("Account Type: Seller");

        product1.setBackground(new java.awt.Color(204, 204, 204));
        product1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        product1.setText("Products");
        product1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SellerProductUI obj = new SellerProductUI();
                obj.setVisible(true);
            }
        });

        javax.swing.GroupLayout active_sellers1Layout = new javax.swing.GroupLayout(active_sellers1);
        active_sellers1.setLayout(active_sellers1Layout);
        active_sellers1Layout.setHorizontalGroup(
            active_sellers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(active_sellers1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fname_lname1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(account_type1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(product1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        active_sellers1Layout.setVerticalGroup(
            active_sellers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(active_sellers1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(active_sellers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fname_lname1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(account_type1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(product1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addContainerGap())
        );

        active_sellers2.setBackground(new java.awt.Color(255, 255, 255));
        active_sellers2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fname_lname2.setText("F. Name L. Name");

        account_type2.setText("Account Type: Seller");

        product2.setBackground(new java.awt.Color(204, 204, 204));
        product2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        product2.setText("Products");
        product2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SellerProductUI obj = new SellerProductUI();
                obj.setVisible(true);
            }
        });

        javax.swing.GroupLayout active_sellers2Layout = new javax.swing.GroupLayout(active_sellers2);
        active_sellers2.setLayout(active_sellers2Layout);
        active_sellers2Layout.setHorizontalGroup(
            active_sellers2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(active_sellers2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fname_lname2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(account_type2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(product2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        active_sellers2Layout.setVerticalGroup(
            active_sellers2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(active_sellers2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(active_sellers2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fname_lname2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(account_type2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(product2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addContainerGap())
        );

        active_sellers3.setBackground(new java.awt.Color(255, 255, 255));
        active_sellers3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fname_lname3.setText("F. Name L. Name");

        account_type3.setText("Account Type: Seller");

        product3.setBackground(new java.awt.Color(204, 204, 204));
        product3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        product3.setText("Products");
        product3.setToolTipText("");
        product3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SellerProductUI obj = new SellerProductUI();
                obj.setVisible(true);
            }
        });

        javax.swing.GroupLayout active_sellers3Layout = new javax.swing.GroupLayout(active_sellers3);
        active_sellers3.setLayout(active_sellers3Layout);
        active_sellers3Layout.setHorizontalGroup(
            active_sellers3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(active_sellers3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fname_lname3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(account_type3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(product3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        active_sellers3Layout.setVerticalGroup(
            active_sellers3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(active_sellers3Layout.createSequentialGroup()
                .addGroup(active_sellers3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(account_type3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(active_sellers3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(active_sellers3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fname_lname3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(product3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))))
                .addContainerGap())
        );

        active_sellers4.setBackground(new java.awt.Color(255, 255, 255));
        active_sellers4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fname_lname4.setText("F. Name L. Name");

        account_type4.setText("Account Type: Seller");

        product4.setBackground(new java.awt.Color(204, 204, 204));
        product4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        product4.setText("Products");
        product4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SellerProductUI obj = new SellerProductUI();
                obj.setVisible(true);
            }
        });

        javax.swing.GroupLayout active_sellers4Layout = new javax.swing.GroupLayout(active_sellers4);
        active_sellers4.setLayout(active_sellers4Layout);
        active_sellers4Layout.setHorizontalGroup(
            active_sellers4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(active_sellers4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fname_lname4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(account_type4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(product4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        active_sellers4Layout.setVerticalGroup(
            active_sellers4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(active_sellers4Layout.createSequentialGroup()
                .addGroup(active_sellers4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fname_lname4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(active_sellers4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(active_sellers4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(account_type4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(product4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))))
                .addContainerGap())
        );

        active_sellers5.setBackground(new java.awt.Color(255, 255, 255));
        active_sellers5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fname_lname5.setText("F. Name L. Name");

        account_type5.setText("Account Type: Seller");

        product5.setBackground(new java.awt.Color(204, 204, 204));
        product5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        product5.setText("Products");
        product5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SellerProductUI obj = new SellerProductUI();
                obj.setVisible(true);
            }
        });

        javax.swing.GroupLayout active_sellers5Layout = new javax.swing.GroupLayout(active_sellers5);
        active_sellers5.setLayout(active_sellers5Layout);
        active_sellers5Layout.setHorizontalGroup(
            active_sellers5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(active_sellers5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fname_lname5, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(account_type5, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(product5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        active_sellers5Layout.setVerticalGroup(
            active_sellers5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(active_sellers5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(active_sellers5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fname_lname5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(account_type5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(product5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addContainerGap())
        );

        active_sellers6.setBackground(new java.awt.Color(255, 255, 255));
        active_sellers6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fname_lname6.setText("F. Name L. Name");

        account_type6.setText("Account Type: Seller");

        product6.setBackground(new java.awt.Color(204, 204, 204));
        product6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        product6.setText("Products");
        product6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SellerProductUI obj = new SellerProductUI();
                obj.setVisible(true);
            }
        });
        javax.swing.GroupLayout active_sellers6Layout = new javax.swing.GroupLayout(active_sellers6);
        active_sellers6.setLayout(active_sellers6Layout);
        active_sellers6Layout.setHorizontalGroup(
            active_sellers6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(active_sellers6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fname_lname6, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(account_type6, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(product6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        active_sellers6Layout.setVerticalGroup(
            active_sellers6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(active_sellers6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(active_sellers6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fname_lname6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(account_type6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(product6, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addContainerGap())
        );

        active_sellers7.setBackground(new java.awt.Color(255, 255, 255));
        active_sellers7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fname_lname7.setText("F. Name L. Name");

        account_type7.setText("Account Type: Seller");

        product7.setBackground(new java.awt.Color(204, 204, 204));
        product7.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        product7.setText("Products");
        product7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SellerProductUI obj = new SellerProductUI();
                obj.setVisible(true);
            }
        });

        javax.swing.GroupLayout active_sellers7Layout = new javax.swing.GroupLayout(active_sellers7);
        active_sellers7.setLayout(active_sellers7Layout);
        active_sellers7Layout.setHorizontalGroup(
            active_sellers7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(active_sellers7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fname_lname7, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(account_type7, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(product7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        active_sellers7Layout.setVerticalGroup(
            active_sellers7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(active_sellers7Layout.createSequentialGroup()
                .addGroup(active_sellers7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(account_type7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(active_sellers7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(active_sellers7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fname_lname7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(product7, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))))
                .addContainerGap())
        );

        active_sellers8.setBackground(new java.awt.Color(255, 255, 255));
        active_sellers8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fname_lname8.setText("F. Name L. Name");

        account_type8.setText("Account Type: Seller");

        product8.setBackground(new java.awt.Color(204, 204, 204));
        product8.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        product8.setText("Products");
        product8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SellerProductUI obj = new SellerProductUI();
                obj.setVisible(true);
            }
        });

        javax.swing.GroupLayout active_sellers8Layout = new javax.swing.GroupLayout(active_sellers8);
        active_sellers8.setLayout(active_sellers8Layout);
        active_sellers8Layout.setHorizontalGroup(
            active_sellers8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(active_sellers8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fname_lname8, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(account_type8, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 365, Short.MAX_VALUE)
                .addComponent(product8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        active_sellers8Layout.setVerticalGroup(
            active_sellers8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(active_sellers8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(active_sellers8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fname_lname8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(account_type8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(product8, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout active_sellersPaneLayout = new javax.swing.GroupLayout(active_sellersPane);
        active_sellersPane.setLayout(active_sellersPaneLayout);
        active_sellersPaneLayout.setHorizontalGroup(
            active_sellersPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(active_sellersPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(active_sellersPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(active_sellers8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(active_sellers7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(active_sellers6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(active_sellers5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(active_sellers4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(active_sellers3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(active_sellers2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(active_sellers1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        active_sellersPaneLayout.setVerticalGroup(
            active_sellersPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(active_sellersPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(active_sellers1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(active_sellers2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(active_sellers3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(active_sellers4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(active_sellers5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(active_sellers6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(active_sellers7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(active_sellers8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        back_button.setBackground(new java.awt.Color(102, 102, 102));
        back_button.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        back_button.setText("Back");
        back_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminPanelUI obj = new AdminPanelUI();
                obj.setVisible(true);
            }
        });

        javax.swing.GroupLayout contentPaneLayout = new javax.swing.GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(active_sellersPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(menuPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentPaneLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(active_sellersPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void create_new_userActionPerformed(ActionEvent evt){
        CreateNewUserUI obj = new CreateNewUserUI();
        obj.setVisible(true);
    }
    private void pending_sellersActionPerformed(ActionEvent evt) {
        PendingSellersUI obj = new PendingSellersUI();
        obj.setVisible(true);
    }
    private void ordersActionPerformed(ActionEvent evt){
        OrdersUI obj = new OrdersUI();
        obj.setVisible(true);
    }
       public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActiveSellersUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActiveSellersUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActiveSellersUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActiveSellersUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActiveSellersUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel account_type1;
    private javax.swing.JLabel account_type2;
    private javax.swing.JLabel account_type3;
    private javax.swing.JLabel account_type4;
    private javax.swing.JLabel account_type5;
    private javax.swing.JLabel account_type6;
    private javax.swing.JLabel account_type7;
    private javax.swing.JLabel account_type8;
    private javax.swing.JButton active_sellers;
    private javax.swing.JPanel active_sellers1;
    private javax.swing.JPanel active_sellers2;
    private javax.swing.JPanel active_sellers3;
    private javax.swing.JPanel active_sellers4;
    private javax.swing.JPanel active_sellers5;
    private javax.swing.JPanel active_sellers6;
    private javax.swing.JPanel active_sellers7;
    private javax.swing.JPanel active_sellers8;
    private javax.swing.JPanel active_sellersPane;
    private javax.swing.JButton back_button;
    private javax.swing.JPanel contentPane;
    private javax.swing.JButton create_new_user;
    private javax.swing.JLabel fname_lname1;
    private javax.swing.JLabel fname_lname2;
    private javax.swing.JLabel fname_lname3;
    private javax.swing.JLabel fname_lname4;
    private javax.swing.JLabel fname_lname5;
    private javax.swing.JLabel fname_lname6;
    private javax.swing.JLabel fname_lname7;
    private javax.swing.JLabel fname_lname8;
    private javax.swing.JPanel menuPane;
    private javax.swing.JButton orders;
    private javax.swing.JButton pending_sellers;
    private javax.swing.JButton product1;
    private javax.swing.JButton product2;
    private javax.swing.JButton product3;
    private javax.swing.JButton product4;
    private javax.swing.JButton product5;
    private javax.swing.JButton product6;
    private javax.swing.JButton product7;
    private javax.swing.JButton product8;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        
        
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
